{{- if .Values.rbac }}
apiVersion: v1
kind: List
items:
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRole
  metadata:
    name: {{ template "serviceaccount" . }}
  rules:
  - apiGroups: [""]
    resources:
    - namespaces
    - services
    - endpoints
    - pods
    verbs: ["list", "get"]
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRoleBinding
  metadata:
    name: {{ template "serviceaccount" . }}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: {{ template "serviceaccount" . }}
  subjects:
  - kind: ServiceAccount
    name: {{ template "serviceaccount" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
